---
# Configure auditbeat Node

#Create required directories
# - name: Create Directories
#   become: true
#   file: path={{ item }} state=directory owner={{ ab_user }} group={{ ab_group }}
#   with_items:
#     - "{{pid_dir}}"
#     - "{{log_dir}}"
#     - "{{conf_dir}}"

#Copy the config template
- name: Auditbeat-config - Copy Configuration File
  become: true
  template: src=auditbeat/auditbeat.yml.j2 dest={{conf_dir}}/auditbeat.yml owner={{ ab_user }} group={{ ab_group }} mode=0644 force=yes
  register: system_change
  notify: restart auditbeat

- name: Auditbeat-config - Create empty default environment file
  become: true
  changed_when: False
  copy:
    dest: /etc/default/auditbeat
    content: ''
  when: ansible_os_family == 'Debian'

- name: Auditbeat-config - Create empty default environment file
  become: true
  changed_when: False
  copy:
    dest: /etc/sysconfig/auditbeat
    content: ''
  when: ansible_os_family == 'RedHat'